// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukjwczykykrobabzzaoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrandjenlreWtyb2JhYnp6YW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODYyMzIsImV4cCI6MjA2NTA2MjIzMn0.6EAkf4pGqUMo0ZC0vOSsjId3mIZFQCtnZ_wLPLc_m9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);